"""
Active Price Monitor orchestrator.

Coordinates all monitor subcomponents:
- TickAggregator (builds bars from ticks)
- IndicatorEngine (computes ATR, EMA, RSI, etc.)
- AnomalyDetector (flags unusual price action)
- StopWatcher (monitors positions for stop/target hits)
- CrossPriceMonitor (tracks correlation shifts)
- FundingWatcher (monitors Hyperliquid funding rates)

Receives ticks/order books/funding rates from venue adapters, feeds them
through all monitors, collects events, and writes to DuckDB + Redis.

See roadmap §2.8 for full design.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator
from datetime import datetime, timezone
from typing import Any

import structlog

from hermes.core.config import HermesConfig
from hermes.db.migrate import get_duckdb_path, safe_duckdb_connect
from hermes.monitor.anomaly_detector import AnomalyDetector
from hermes.monitor.cross_price import CrossPriceMonitor
from hermes.monitor.funding_watcher import FundingWatcher
from hermes.monitor.indicators import IndicatorEngine
from hermes.monitor.stop_watcher import StopWatcher
from hermes.monitor.tick_aggregator import TickAggregator
from hermes.schemas.market import (
    Bar,
    FundingRate,
    OrderBookL2,
    Position,
    PriceMonitorEvent,
    Tick,
    Venue,
)

log = structlog.get_logger(__name__)


class PriceMonitor:
    """
    Orchestrates all Active Price Monitor subcomponents.

    Usage:
        monitor = PriceMonitor(config)
        await monitor.start()
        await monitor.on_tick(tick)  # from venue adapter
        await monitor.on_order_book(book)
        await monitor.on_funding(funding)
        events = monitor.get_pending_events()
    """

    def __init__(self, config: HermesConfig) -> None:
        self._config = config
        self._db_path = get_duckdb_path(config)

        # Sub-components
        self._aggregator = TickAggregator(
            timeframes=["1s", "5s", "1m", "5m", "15m", "1h"],
            window_size=500,
        )
        self._indicators = IndicatorEngine(max_bars_per_symbol=500)
        self._anomaly_detector = AnomalyDetector()
        self._stop_watcher = StopWatcher()
        self._cross_price = CrossPriceMonitor()
        self._funding_watcher = FundingWatcher()

        # Event buffer
        self._pending_events: list[PriceMonitorEvent] = []
        self._event_queue: asyncio.Queue[PriceMonitorEvent] = asyncio.Queue()

        # Internal Redis for event publishing
        self._redis = None
        self._redis_url = config.hermes_redis.get("url", "redis://localhost:6379/1")

        self._running = False
        self._writer_task: asyncio.Task | None = None

        self._stats = {
            "ticks_processed": 0,
            "books_processed": 0,
            "funding_processed": 0,
            "events_emitted": 0,
            "bars_closed": 0,
        }

    async def start(self) -> None:
        """Start the monitor (connect to Redis for event publishing)."""
        if self._running:
            return
        self._running = True

        # Connect to internal Redis for event publishing
        if not ("<" in self._redis_url or self._redis_url.startswith("secret:")):
            try:
                import redis.asyncio as aioredis

                self._redis = aioredis.from_url(
                    self._redis_url, decode_responses=True
                )
                await self._redis.ping()
                log.info("monitor_redis_connected")
            except Exception as e:
                log.warning("monitor_redis_unavailable", error=str(e))
                self._redis = None

        # Start background event writer
        self._writer_task = asyncio.create_task(self._event_writer_loop())

        log.info("price_monitor_started")

    async def stop(self) -> None:
        """Stop the monitor."""
        self._running = False
        if self._writer_task:
            self._writer_task.cancel()
            try:
                await self._writer_task
            except asyncio.CancelledError:
                pass
        if self._redis:
            await self._redis.close()
        log.info("price_monitor_stopped", stats=self._stats)

    async def on_tick(self, tick: Tick) -> list[PriceMonitorEvent]:
        """
        Process a tick through all monitors.
        Returns events generated by this tick.
        """
        self._stats["ticks_processed"] += 1
        events: list[PriceMonitorEvent] = []

        # 1. Tick aggregator (builds bars)
        closed_bars = self._aggregator.on_tick(tick)
        if closed_bars:
            self._stats["bars_closed"] += len(closed_bars)
            # Feed closed bars to indicator engine
            for bar in closed_bars:
                self._indicators.on_bar(bar)

        # 2. Anomaly detection
        anomaly = self._anomaly_detector.on_tick(tick)
        if anomaly:
            events.append(anomaly)

        # 3. Stop/target watcher
        # Get current ATR for trailing stop computation
        atr = self._indicators.get_atr(tick.symbol, "1m")
        stop_events = self._stop_watcher.on_tick(tick, current_atr=atr)
        events.extend(stop_events)

        # 4. Cross-price correlation
        corr_event = self._cross_price.on_tick(tick)
        if corr_event:
            events.append(corr_event)

        # Enqueue events for writing/publishing
        for event in events:
            await self._event_queue.put(event)
            self._stats["events_emitted"] += 1

        return events

    async def on_order_book(self, book: OrderBookL2) -> list[PriceMonitorEvent]:
        """Process an order book update."""
        self._stats["books_processed"] += 1
        events: list[PriceMonitorEvent] = []

        # Anomaly detection on order book
        anomaly = self._anomaly_detector.on_order_book(book)
        if anomaly:
            events.append(anomaly)

        for event in events:
            await self._event_queue.put(event)
            self._stats["events_emitted"] += 1

        return events

    async def on_funding(self, funding: FundingRate) -> list[PriceMonitorEvent]:
        """Process a funding rate update."""
        self._stats["funding_processed"] += 1
        events: list[PriceMonitorEvent] = []

        spike = self._funding_watcher.on_funding(funding)
        if spike:
            events.append(spike)

        for event in events:
            await self._event_queue.put(event)
            self._stats["events_emitted"] += 1

        return events

    def add_position(self, position: Position) -> None:
        """Register a position for stop/target monitoring."""
        self._stop_watcher.add_position(position)

    def remove_position(self, position_id: str) -> None:
        """Remove a position from monitoring."""
        self._stop_watcher.remove_position(position_id)

    def get_last_price(self, symbol: str) -> float | None:
        """Get the last known price for a symbol."""
        return self._aggregator.get_last_price(symbol)

    def get_indicators(self, symbol: str, timeframe: str = "1m") -> dict[str, float | None]:
        """Get all current indicators for a symbol."""
        return self._indicators.get_all_indicators(symbol, timeframe)

    def get_bars(self, symbol: str, timeframe: str, n: int = 100) -> list[Bar]:
        """Get recent bars for a symbol."""
        return self._aggregator.get_bars(symbol, timeframe, n)

    def get_correlation_matrix(self) -> dict[str, dict[str, float]]:
        """Get current correlation matrix across all symbols."""
        return self._cross_price.get_correlation_matrix()

    def get_current_funding(self, symbol: str) -> FundingRate | None:
        """Get latest funding rate for a symbol."""
        return self._funding_watcher.get_current_funding(symbol)

    def get_positions(self) -> list[Position]:
        """Get all monitored positions."""
        return self._stop_watcher.get_positions()

    def get_stats(self) -> dict[str, Any]:
        """Get monitor statistics."""
        stats = self._stats.copy()
        stats["aggregator"] = self._aggregator.get_stats()
        stats["anomaly_detector"] = self._anomaly_detector.get_stats()
        stats["stop_watcher"] = self._stop_watcher.get_stats()
        stats["cross_price"] = self._cross_price.get_stats()
        stats["funding_watcher"] = self._funding_watcher.get_stats()
        return stats

    async def _event_writer_loop(self) -> None:
        """Background loop: batch-write events to DuckDB + publish to Redis."""
        batch: list[PriceMonitorEvent] = []
        while self._running:
            try:
                # Wait for events with timeout
                event = await asyncio.wait_for(self._event_queue.get(), timeout=1.0)
                batch.append(event)
            except asyncio.TimeoutError:
                pass

            # Flush if we have events
            if batch:
                await self._flush_events(batch[:])
                batch.clear()

        # Final flush
        if batch:
            await self._flush_events(batch)

    async def _flush_events(self, events: list[PriceMonitorEvent]) -> None:
        """Write events to DuckDB and publish to Redis."""
        # Write to DuckDB (in executor to avoid blocking)
        await asyncio.get_event_loop().run_in_executor(
            None, self._write_events_to_duckdb, events
        )

        # Publish to Redis (best-effort)
        if self._redis:
            for event in events:
                try:
                    channel = f"price.{event.event_type}.{event.symbol}"
                    payload = event.model_dump(mode="json")
                    await self._redis.publish(channel, json.dumps(payload, default=str))
                except Exception as e:
                    log.warning("event_publish_failed", error=str(e))

    def _write_events_to_duckdb(self, events: list[PriceMonitorEvent]) -> None:
        """Write events to DuckDB price_monitor_events table."""
        import duckdb

        try:
            with safe_duckdb_connect(str(self._db_path)) as conn:
                for event in events:
                    conn.execute(
                        """
                        INSERT INTO price_monitor_events (
                            event_id, ts, symbol, venue, event_type, severity,
                            last_price, spread_bps, book_imbalance,
                            realized_vol_1m, realized_vol_1h, atr_14,
                            payload, position_id, related_symbols, meta_regime_at_event
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        [
                            event.event_id,
                            event.ts,
                            event.symbol,
                            event.venue.value,
                            event.event_type,
                            event.severity,
                            event.last_price,
                            event.spread_bps,
                            event.book_imbalance,
                            event.realized_vol_1m,
                            event.realized_vol_1h,
                            event.atr_14,
                            json.dumps(event.payload, default=str),
                            event.position_id,
                            event.related_symbols,
                            event.meta_regime_at_event,
                        ],
                    )
        except Exception as e:
            log.error("events_duckdb_write_failed", error=str(e), n_events=len(events))
